import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/public/assets/css/style.css";
import "@/public/assets/css/responsive.css";
import Header from "@/components/Header";
import ScriptLoader from "@/components/ScriptLoader";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lucent Industrial Solutions",
  description: "Generated by create next appWe are a dynamic instrumentation and control automation company, established in 2024 in the Emirate of Dubai, United Arab Emirates. We specialise in providing cutting-edge solutions in measuring and controlling systems, catering to a wide range of industries.",
  icons: {
    icon: "/assets/img/favicon.png",
    shortcut: "/assets/img/favicon.png",
    apple: "/assets/img/favicon.png",
  },
  keywords: [
    "Lucent Industrial Solutions",
    "Instrumentation and Control Automation",
    "Dubai",
    "UAE",
    "Automation Solutions",
    "Industrial Solutions",
    "Measuring Systems",
    "Control Systems",
    "Cutting-edge Solutions",
    "Industry Specialists",
    "Established in 2024",
    "Dynamic Company",
    "Innovative Solutions",
    "Industrial Automation",
    "Instrumentation Specialists",
    "Control Systems Experts",
    "Dubai Industry Leaders",
    "UAE Automation Experts",
    "Advanced Measuring Systems",
    "Precision Control Solutions",
    "Industrial Innovation",
    "Automation Technology",
  ],
  openGraph: {
    title: "Lucent Industrial Solutions",
    description: "We are a dynamic instrumentation and control automation company, established in 2024 in the Emirate of Dubai, United Arab Emirates. We specialise in providing cutting-edge solutions in measuring and controlling systems, catering to a wide range of industries.",
    url: "https://lucent-is.com",
    siteName: "Lucent Industrial Solutions",
    images: [
      {
        url: "https://lucent-is.com/assets/img/logo.png",
        width: 800,
        height: 600,
        alt: "Lucent Industrial Solutions Logo",
      },
    ],
  },
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.png" />
        <link rel="canonical" href="Lucent" />
        <link rel="preconnect" href="https://fonts.googleapis.com/" />
        <link rel="preconnect" href="https://fonts.gstatic.com/" />
        <link href="https://fonts.googleapis.com/css2?family=Yantramanav:wght@100;300;400;500;700;900&amp;display=swap"
          rel="stylesheet" />
        <link rel="stylesheet" href="assets/vendors/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="assets/vendors/animate/animate.min.css" />
        <link rel="stylesheet" href="assets/vendors/animate/custom-animate.css" />
        <link rel="stylesheet" href="assets/vendors/fontawesome/css/all.min.css" />
        <link rel="stylesheet" href="assets/vendors/jarallax/jarallax.css" />
        <link rel="stylesheet" href="assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css" />
        <link rel="stylesheet" href="assets/vendors/odometer/odometer.min.css" />
        <link rel="stylesheet" href="assets/vendors/swiper/swiper.min.css" />
        <link rel="stylesheet" href="assets/vendors/elitecons-icons/style.css" />
        <link rel="stylesheet" href="assets/vendors/owl-carousel/owl.carousel.min.css" />
        <link rel="stylesheet" href="assets/vendors/owl-carousel/owl.theme.default.min.css" />
        <link rel="stylesheet" href="assets/vendors/bootstrap-select/css/bootstrap-select.min.css" />
        <link rel="stylesheet" href="assets/vendors/nice-select/nice-select.css" />
        <link rel="stylesheet" href="assets/vendors/jquery-ui/jquery-ui.css" />
        <link rel="stylesheet" href="assets/css/style.css" />
        <link rel="stylesheet" href="assets/css/responsive.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased custom-cursor`}
      >
        <div className="custom-cursor__cursor"></div>
        <div className="custom-cursor__cursor-two"></div>
        <div
          className="page-wrapper"
        >
          <Header />
          {children}
          <Footer />
        </div>
        <ScriptLoader />
      </body>
    </html>
  );
}
